app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
	return redirect()->to('tv/page1');
});

Route::group(['prefix' => 'tv'], function () {
	Route::get('page1', ['as' => 'page1', 'uses' => 'TVController@page1']);
	Route::get('page2', ['as' => 'page2', 'uses' => 'TVController@page2']);
	Route::get('page3', ['as' => 'page3', 'uses' => 'TVController@page3']);
        Route::get('page4', ['as' => 'page4', 'uses' => 'TVController@page4']);
        Route::get('page5', ['as' => 'page5', 'uses' => 'TVController@page5']);
});

Route::group(['prefix' => 'api'], function () {
	Route::get('map_data', ['as' => 'map_data', 'uses' => 'APIController@mapData']);
});

Route::group(['prefix' => 'admin'], function () {
	Route::get('rss_items/import', ['as' => 'admin.rss_items.import', 'uses' => 'RSSItemController@import']);
        
	Route::resource("rss_items","RSSItemController");
	Route::resource("partners","PartnerController");
	Route::resource("single_values","SingleValueController");
	Route::resource("operations","OperationController");
        Route::resource("snap_shots","PhotoController");
	Route::group(['prefix' => 'import'], function () {
		Route::get('/', ['as' => 'admin.import.index', 'uses' => 'ImportController@import']);
		Route::post('post', ['as' => 'admin.import.importPost', 'uses' => 'ImportController@importPost']);
                
	});
        Route::group(['prefix' => 'snap_shots'], function () {
		Route::get('/', ['as' => 'admin.snap_shots.index', 'uses' => 'PhotoController@snap_shots']);
                Route::post('post', ['as' => 'admin.image.upload', 'uses' => 'PhotoController@upload']);
                
	});
        
});

app/Models/SingleValue.php
<?php

namespace Dashboard\Models;

use Illuminate\Database\Eloquent\Model;

class SingleValue extends Model
{
    protected $primaryKey = 'key';
    public $incrementing = false;
    public $timestamps = false;
}

app/Http/Controllers/SingleValueController.php
<?php

namespace Dashboard\Http\Controllers;

use Dashboard\Http\Requests;
use Dashboard\Http\Controllers\Controller;

use Dashboard\Models\SingleValue as SingleValue;
use Illuminate\Http\Request;

class SingleValueController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$single_values = SingleValue::orderBy('key', 'desc')->paginate(10);

		return view('single_values.index', compact('single_values'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('single_values.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$single_value = new SingleValue();

		$single_value->key = $request->input("key");
        $single_value->value = $request->input("value");

		$single_value->save();

		return redirect()->route('admin.single_values.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$single_value = SingleValue::findOrFail($id);

		return view('single_values.show', compact('single_value'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$single_value = SingleValue::findOrFail($id);

		return view('single_values.edit', compact('single_value'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$single_value = SingleValue::findOrFail($id);

		$single_value->key = $request->input("key");
        $single_value->value = $request->input("value");

		$single_value->save();

		return redirect()->route('admin.single_values.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$single_value = SingleValue::findOrFail($id);
		$single_value->delete();

		return redirect()->route('admin.single_values.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/single_values/create.blade.php
@extends('layouts.admin')
@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
<div class="page-header">
    <h1><i class="glyphicon glyphicon-plus"></i> SingleValues / Create </h1>
</div>
@endsection

@section('content')
@include('error')

<div class="row">
    <div class="col-md-12">

        <form action="{{ route('admin.single_values.store') }}" method="POST">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <div class="form-group @if($errors->has('key')) has-error @endif">
                <label for="key-field">Key</label>
                <input type="text" id="key-field" name="key" class="form-control" value="{{ old("key") }}"/>
                @if($errors->has("key"))
                <span class="help-block">{{ $errors->first("key") }}</span>
                @endif
            </div>

            <div class="form-group @if($errors->has('value')) has-error @endif">
                <label for="value-field">Value</label>
                <input type="text" id="value-field" name="value" class="form-control" value="{{ old("value") }}"/>
                @if($errors->has("value"))
                <span class="help-block">{{ $errors->first("value") }}</span>
                @endif
            </div>

            <div class="well well-sm">
                <button type="submit" class="btn btn-primary">Create</button>
                <a class="btn btn-link pull-right" href="{{ route('admin.single_values.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
            </div>
        </form>

    </div>
</div>
@endsection
@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
<script>
    $('.date-picker').datepicker({
    });
</script>
@endsection

resources/views/single_values/edit.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> SingleValues / Edit #{{$single_value->key}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('admin.single_values.update', $single_value->key) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">


            <div class="form-group @if($errors->has('key')) has-error @endif">
                <label for="key-field">Key</label>
                <input type="text" id="key-field" name="key" class="form-control" value="{{ is_null(old("key")) ? $single_value->key : old("key") }}"/>
                @if($errors->has("key"))
                <span class="help-block">{{ $errors->first("key") }}</span>
                @endif
            </div>

            <div class="form-group @if($errors->has('value')) has-error @endif">
                <label for="value-field">Value</label>
                <input type="text" id="value-field" name="value" class="form-control" value="{{ is_null(old("value")) ? $single_value->value : old("value") }}"/>
                @if($errors->has("value"))
                <span class="help-block">{{ $errors->first("value") }}</span>
                @endif
            </div>
                
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('admin.single_values.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/single_values/index.blade.php
@extends('layouts.admin')
@section('title', 'UNHRD Dashboard - Single Values')
@section('header')
    <div class="clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Single Values
            <a class="btn btn-success pull-right" href="{{ route('admin.single_values.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($single_values->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>KEY</th>
                            <th>VALUE</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($single_values as $single_value)
                            <tr>
                                <td>{{$single_value->key}}</td>
                                <td>{{$single_value->value}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.single_values.show', $single_value->key) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('admin.single_values.edit', $single_value->key) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('admin.single_values.destroy', $single_value->key) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $single_values->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/single_values/show.blade.php
@extends('layouts.admin')
@section('header')
<div class="page-header">
        <h1>SingleValues / Show #{{$single_value->id}}</h1>
        <form action="{{ route('admin.single_values.destroy', $single_value->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('admin.single_values.edit', $single_value->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                
            </form>

            <a class="btn btn-link" href="{{ route('admin.single_values.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection