app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
	return redirect()->to('tv/page1');
});

Route::group(['prefix' => 'tv'], function () {
	Route::get('page1', ['as' => 'page1', 'uses' => 'TVController@page1']);
	Route::get('page2', ['as' => 'page2', 'uses' => 'TVController@page2']);
	Route::get('page3', ['as' => 'page3', 'uses' => 'TVController@page3']);
        Route::get('page4', ['as' => 'page4', 'uses' => 'TVController@page4']);
        Route::get('page5', ['as' => 'page5', 'uses' => 'TVController@page5']);
});

Route::group(['prefix' => 'api'], function () {
	Route::get('map_data', ['as' => 'map_data', 'uses' => 'APIController@mapData']);
});

Route::group(['prefix' => 'admin'], function () {
	Route::get('rss_items/import', ['as' => 'admin.rss_items.import', 'uses' => 'RSSItemController@import']);
        
	Route::resource("rss_items","RSSItemController");
	Route::resource("partners","PartnerController");
	Route::resource("single_values","SingleValueController");
	Route::resource("operations","OperationController");
        Route::resource("snap_shots","PhotoController");
	Route::group(['prefix' => 'import'], function () {
		Route::get('/', ['as' => 'admin.import.index', 'uses' => 'ImportController@import']);
		Route::post('post', ['as' => 'admin.import.importPost', 'uses' => 'ImportController@importPost']);
                
	});
        Route::group(['prefix' => 'snap_shots'], function () {
		Route::get('/', ['as' => 'admin.snap_shots.index', 'uses' => 'PhotoController@snap_shots']);
                Route::post('post', ['as' => 'admin.image.upload', 'uses' => 'PhotoController@upload']);
                
	});
        
});

app/Models/Partner.php
<?php

namespace Dashboard\Models;

use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    protected $guard = array();
}

app/Http/Controllers/PartnerController.php
<?php

namespace Dashboard\Http\Controllers;

use Dashboard\Http\Requests;
use Dashboard\Http\Controllers\Controller;

use Dashboard\Models\Partner;
use Illuminate\Http\Request;

class PartnerController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$partners = Partner::orderBy('name')->paginate(20);

		return view('partners.index', compact('partners'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('partners.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$partner = new Partner();

		$partner->code = $request->input("code");
                $partner->name = $request->input("name");

                $imageName = $partner->code . '.' . $request->file('logo')->getClientOriginalExtension();
                $imageDestination = public_path("images/partners");
                $request->file('logo')->move($imageDestination, $imageName);
                $partner->logo = 'images/partners/'.$imageName;

		$partner->save();

		return redirect()->route('admin.partners.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$partner = Partner::findOrFail($id);

		return view('partners.show', compact('partner'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$partner = Partner::findOrFail($id);

		return view('partners.edit', compact('partner'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$partner = Partner::findOrFail($id);

		$partner->code = $request->input("code");
                $partner->name = $request->input("name");

                $imageName = $partner->code . '.' . $request->file('logo')->getClientOriginalExtension();
                $imageDestination = public_path("images/partners");
                $request->file('logo')->move($imageDestination, $imageName);
                $partner->logo = 'images/partners/'.$imageName;

		$partner->save();

		return redirect()->route('admin.partners.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$partner = Partner::findOrFail($id);
		$partner->delete();

		return redirect()->route('admin.partners.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/partners/create.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Partners / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('admin.partners.store') }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('code')) has-error @endif">
                       <label for="code-field">Code</label>
                    <input type="text" id="code-field" name="code" class="form-control" value="{{ old("code") }}"/>
                       @if($errors->has("code"))
                        <span class="help-block">{{ $errors->first("code") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('logo')) has-error @endif">
                       <label for="logo-field">Logo</label>
                      <input type="file" id="logo-field" name="logo" />
                       @if($errors->has("logo"))
                        <span class="help-block">{{ $errors->first("logo") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('admin.partners.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/partners/edit.blade.php
@extends('layouts.admin')
@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
<div class="page-header">
  <h1><i class="glyphicon glyphicon-edit"></i> Partners / Edit #{{$partner->id}}</h1>
</div>
@endsection

@section('content')
@include('error')

<div class="row">
  <div class="col-md-12">

    <form action="{{ route('admin.partners.update', $partner->id) }}" method="POST" enctype="multipart/form-data">
      <input type="hidden" name="_method" value="PUT">
      <input type="hidden" name="_token" value="{{ csrf_token() }}">

      <div class="form-group @if($errors->has('code')) has-error @endif">
       <label for="code-field">Code</label>
       <input type="text" id="code-field" name="code" class="form-control" value="{{ is_null(old("code")) ? $partner->code : old("code") }}"/>
       @if($errors->has("code"))
       <span class="help-block">{{ $errors->first("code") }}</span>
       @endif
     </div>
     <div class="form-group @if($errors->has('name')) has-error @endif">
       <label for="name-field">Name</label>
       <input type="text" id="name-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $partner->name : old("name") }}"/>
       @if($errors->has("name"))
       <span class="help-block">{{ $errors->first("name") }}</span>
       @endif
     </div>
     <div class="form-group @if($errors->has('logo')) has-error @endif">
       <label for="logo-field">Logo</label>
       <input type="file" id="logo-field" name="logo" />
       @if($errors->has("logo"))
       <span class="help-block">{{ $errors->first("logo") }}</span>
       @endif
     </div>
     <div class="well well-sm">
      <button type="submit" class="btn btn-primary">Save</button>
      <a class="btn btn-link pull-right" href="{{ route('admin.partners.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
    </div>
  </form>

</div>
</div>
@endsection
@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
<script>
  $('.date-picker').datepicker({
  });
</script>
@endsection

resources/views/partners/index.blade.php
@extends('layouts.admin')
@section('title', 'UNHRD Dashboard - Partners')
@section('header')
    <div class="clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Partners
            <a class="btn btn-success pull-right" href="{{ route('admin.partners.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($partners->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>CODE</th>
                        <th>NAME</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($partners as $partner)
                            <tr>
                                <td>{{$partner->code}}</td>
                    <td>{{$partner->name}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.partners.show', $partner->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('admin.partners.edit', $partner->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('admin.partners.destroy', $partner->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $partners->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/partners/show.blade.php
@extends('layouts.admin')
@section('header')
<div class="page-header">
        <h1>Partners / Show #{{$partner->id}}</h1>
        <form action="{{ route('admin.partners.destroy', $partner->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('admin.partners.edit', $partner->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                     <label for="code">CODE</label>
                     <p class="form-control-static">{{$partner->code}}</p>
                </div>
                    <div class="form-group">
                     <label for="name">NAME</label>
                     <p class="form-control-static">{{$partner->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="logo">LOGO</label>
                     <p class="form-control-static">{{ Html::Image($partner->logo) }}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('admin.partners.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection