app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
	return redirect()->to('tv/page1');
});

Route::group(['prefix' => 'tv'], function () {
	Route::get('page1', ['as' => 'page1', 'uses' => 'TVController@page1']);
	Route::get('page2', ['as' => 'page2', 'uses' => 'TVController@page2']);
	Route::get('page3', ['as' => 'page3', 'uses' => 'TVController@page3']);
        Route::get('page4', ['as' => 'page4', 'uses' => 'TVController@page4']);
        Route::get('page5', ['as' => 'page5', 'uses' => 'TVController@page5']);
});

Route::group(['prefix' => 'api'], function () {
	Route::get('map_data', ['as' => 'map_data', 'uses' => 'APIController@mapData']);
});

Route::group(['prefix' => 'admin'], function () {
	Route::get('rss_items/import', ['as' => 'admin.rss_items.import', 'uses' => 'RSSItemController@import']);
        
	Route::resource("rss_items","RSSItemController");
	Route::resource("partners","PartnerController");
	Route::resource("single_values","SingleValueController");
	Route::resource("operations","OperationController");
        Route::resource("snap_shots","PhotoController");
	Route::group(['prefix' => 'import'], function () {
		Route::get('/', ['as' => 'admin.import.index', 'uses' => 'ImportController@import']);
		Route::post('post', ['as' => 'admin.import.importPost', 'uses' => 'ImportController@importPost']);
                
	});
        Route::group(['prefix' => 'snap_shots'], function () {
		Route::get('/', ['as' => 'admin.snap_shots.index', 'uses' => 'PhotoController@snap_shots']);
                Route::post('post', ['as' => 'admin.image.upload', 'uses' => 'PhotoController@upload']);
                
	});
        
});

app/Models/Operation.php
<?php

namespace Dashboard\Models;

use Illuminate\Database\Eloquent\Model;

class Operation extends Model
{
    protected $guard = array();
}

app/Http/Controllers/OperationController.php
<?php

namespace Dashboard\Http\Controllers;

use Dashboard\Http\Requests;
use Dashboard\Http\Controllers\Controller;

use Dashboard\Models\Operation;
use Illuminate\Http\Request;

class OperationController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$operations = Operation::orderBy('id', 'desc')->paginate(10);

		return view('operations.index', compact('operations'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('operations.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$operation = new Operation();

		$operation->name = $request->input("name");
                $operation->start_date = $request->input("start_date");
                $operation->level = $request->input("level");
                $operation->volume = $request->input("volume");
                $operation->value = $request->input("value");
                $operation->weight = $request->input("weight");
                $operation->partners = $request->input("partners");

		$operation->save();

		return redirect()->route('admin.operations.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$operation = Operation::findOrFail($id);

		return view('operations.show', compact('operation'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$operation = Operation::findOrFail($id);

		return view('operations.edit', compact('operation'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$operation = Operation::findOrFail($id);

		$operation->name = $request->input("name");
                $operation->start_date = $request->input("start_date");
                $operation->level = $request->input("level");
                $operation->volume = $request->input("volume");
                $operation->value = $request->input("value");
		$operation->weight = $request->input("weight");
                $operation->partners = $request->input("partners");
               
		$operation->save();

		return redirect()->route('admin.operations.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$operation = Operation::findOrFail($id);
		$operation->delete();

		return redirect()->route('admin.operations.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/operations/create.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Operations / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('admin.operations.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('start_date')) has-error @endif">
                       <label for="start_date">Serving Since</label>
                    <input type="date" id="start_date" name="start_date" class="form-control" value="{{ old("start_date") }}"/>
                       @if($errors->has("start_date"))
                        <span class="help-block">{{ $errors->first("start_date") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('level')) has-error @endif">
                       <label for="level">Emergency Level</label>
                    <input type="text" id="level" name="level" class="form-control" value="{{ old("level") }}"/>
                       @if($errors->has("level"))
                        <span class="help-block">{{ $errors->first("level") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('volume')) has-error @endif">
                       <label for="volume-field">No: of Shipments</label>
                    <input type="text" id="volume-field" name="volume" class="form-control" value="{{ old("volume") }}"/>
                       @if($errors->has("volume"))
                        <span class="help-block">{{ $errors->first("volume") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('weight')) has-error @endif">
                       <label for="weight-field">Weight (MT)</label>
                    <input type="text" id="weight-field" name="weight" class="form-control" value="{{ old("weight") }}"/>
                       @if($errors->has("weight"))
                        <span class="help-block">{{ $errors->first("weight") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('value')) has-error @endif">
                       <label for="value-field">Value (M USD)</label>
                    <input type="text" id="value-field" name="value" class="form-control" value="{{ old("value") }}"/>
                       @if($errors->has("value"))
                        <span class="help-block">{{ $errors->first("value") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('partners')) has-error @endif">
                       <label for="partners-field">Partners</label>
                    <input type="text" id="partners-field" name="partners" class="form-control" value="{{ old("partners") }}"/>
                       @if($errors->has("partners"))
                        <span class="help-block">{{ $errors->first("partners") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('admin.operations.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/operations/edit.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Operations / Edit #{{$operation->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('admin.operations.update', $operation->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $operation->name : old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('start_date')) has-error @endif">
                       <label for="date-field">Serving Since:</label>
                    <input type="date" id="start_date" name="start_date" class="form-control" 
                           value="{{ is_null (old("start_date"))? $operation->start_date : old("start_date") }}"/>
                       @if($errors->has("start_date"))
                        <span class="help-block">{{ $errors->first("start_date") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('level')) has-error @endif">
                       <label for="level">Emergency Level</label>
                    <input type="text" id="level" name="level" class="form-control" value="{{ is_null(old("level")) ? $operation->volume : old("level") }}"/>
                       @if($errors->has("level"))
                        <span class="help-block">{{ $errors->first("level") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('volume')) has-error @endif">
                       <label for="volume-field">No: of Shipments</label>
                    <input type="text" id="volume-field" name="volume" class="form-control" value="{{ is_null(old("volume")) ? $operation->volume : old("volume") }}"/>
                       @if($errors->has("volume"))
                        <span class="help-block">{{ $errors->first("volume") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('weight')) has-error @endif">
                       <label for="weight-field">Weight (MT)</label>
                    <input type="text" id="weight-field" name="weight" class="form-control" value="{{ is_null(old("weight")) ? $operation->weight : old("weight") }}"/>
                       @if($errors->has("weight"))
                        <span class="help-block">{{ $errors->first("weight") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('value')) has-error @endif">
                       <label for="value-field">Value (M USD)</label>
                    <input type="text" id="value-field" name="value" class="form-control" value="{{ is_null(old("value")) ? $operation->value : old("value") }}"/>
                       @if($errors->has("value"))
                        <span class="help-block">{{ $errors->first("value") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('partners')) has-error @endif">
                       <label for="partners-field">Partners</label>
                    <input type="text" id="partners-field" name="partners" class="form-control" value="{{ is_null(old("partners")) ? $operation->partners : old("partners") }}"/>
                       @if($errors->has("partners"))
                        <span class="help-block">{{ $errors->first("partners") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('admin.operations.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/operations/index.blade.php
@extends('layouts.admin')

@section('header')
<div class="page-header clearfix">
    <h1>
        <i class="glyphicon glyphicon-align-justify"></i> Operations
        <a class="btn btn-success pull-right" href="{{ route('admin.operations.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
    </h1>

</div>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        @if($operations->count())
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th>NAME</th>
                    <th class="text-right">OPTIONS</th>
                </tr>
            </thead>

            <tbody>
                @foreach($operations as $operation)
                <tr>
                    <td>{{$operation->name}}</td>
                    <td class="text-right">
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.operations.show', $operation->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                        <a class="btn btn-xs btn-warning" href="{{ route('admin.operations.edit', $operation->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                        <form action="{{ route('admin.operations.destroy', $operation->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {!! $operations->render() !!}
        @else
        <h3 class="text-center alert alert-info">Empty!</h3>
        @endif

    </div>
</div>

@endsection

resources/views/operations/show.blade.php
@extends('layouts.admin')
@section('header')
<div class="page-header">
        <h1>Operations / Show #{{$operation->id}}</h1>
        <form action="{{ route('admin.operations.destroy', $operation->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('admin.operations.edit', $operation->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="name">NAME</label>
                     <p class="form-control-static">{{$operation->name}}</p>
                </div>
                <div class="form-group">
                     <label for="start_date">Serving Since</label>
                     <p class="form-control-static">{{$operation->start_date}}</p>
                </div>
                <div class="form-group">
                     <label for="level">Emergency Level</label>
                     <p class="form-control-static">{{$operation->level}}</p>
                </div>
                <div class="form-group">
                     <label for="volume">No: of Shipments</label>
                     <p class="form-control-static">{{$operation->volume}}</p>
                </div>
                <div class="form-group">
                     <label for="weight">WEIGHT (MT)</label>
                     <p class="form-control-static">{{$operation->weight}}</p>
                </div>
                    <div class="form-group">
                     <label for="value">VALUE (M USD)</label>
                     <p class="form-control-static">{{$operation->value}}</p>
                </div>
                <div class="form-group">
                     <label for="partners">PARTNERS</label>
                     <p class="form-control-static">{{$operation->partners}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('admin.operations.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection