app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
	return redirect()->to('tv/page1');
});

Route::group(['prefix' => 'tv'], function () {
	Route::get('page1', ['as' => 'page1', 'uses' => 'TVController@page1']);
	Route::get('page2', ['as' => 'page2', 'uses' => 'TVController@page2']);
	Route::get('page3', ['as' => 'page3', 'uses' => 'TVController@page3']);
        Route::get('page4', ['as' => 'page4', 'uses' => 'TVController@page4']);
        Route::get('page5', ['as' => 'page5', 'uses' => 'TVController@page5']);
});

Route::group(['prefix' => 'api'], function () {
	Route::get('map_data', ['as' => 'map_data', 'uses' => 'APIController@mapData']);
});

Route::group(['prefix' => 'admin'], function () {
	Route::get('rss_items/import', ['as' => 'admin.rss_items.import', 'uses' => 'RSSItemController@import']);
        
	Route::resource("rss_items","RSSItemController");
	Route::resource("partners","PartnerController");
	Route::resource("single_values","SingleValueController");
	Route::resource("operations","OperationController");
        Route::resource("snap_shots","PhotoController");
	Route::group(['prefix' => 'import'], function () {
		Route::get('/', ['as' => 'admin.import.index', 'uses' => 'ImportController@import']);
		Route::post('post', ['as' => 'admin.import.importPost', 'uses' => 'ImportController@importPost']);
                
	});
        Route::group(['prefix' => 'snap_shots'], function () {
		Route::get('/', ['as' => 'admin.snap_shots.index', 'uses' => 'PhotoController@snap_shots']);
                Route::post('post', ['as' => 'admin.image.upload', 'uses' => 'PhotoController@upload']);
                
	});
        
});

app/Models/RSSItem.php
<?php

namespace Dashboard\Models;

use Illuminate\Database\Eloquent\Model;

class RSSItem extends Model
{
    protected $table = "rss_items";

    protected $visible = ['text'];
}

app/Http/Controllers/RSSItemController.php
<?php

namespace Dashboard\Http\Controllers;

use Illuminate\Http\Request;
use Dashboard\Http\Requests;

use Dashboard\Models\RSSItem;

use SimplePie;

class RSSItemController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
		$rss_items = RSSItem::orderBy('id', 'desc')->paginate(20);

		return view('rss_items.index', compact('rss_items'));
	}

	/**
	 * Import RSS items from the UNHRD RSS feed
	 *
	 * @return Response
	 */
	public function import(Request $request)
	{
		//$feed_url = 'http://unhrd.org/news.xml';
		$feed_url = 'http://www.gdacs.org/xml/rss.xml';

		$simplepie = new SimplePie();
//		$simplepie->set_feed_url($feed_url);
		$simplepie->set_raw_data(preg_replace(array('/\s{2,}/', '/[\t\n]/'), '', file_get_contents($feed_url)));
		$simplepie->init();
		$simplepie->handle_content_type();

		foreach ($simplepie->get_items() as $item) {
			try {
				$rss_item = new RSSItem;
				$rss_item->text = $item->get_title();
				$rss_item->visible = true;
				$rss_item->posted_date = $item->get_gmdate('Y-m-d H:i');
				$rss_item->save();
			} catch(\Illuminate\Database\QueryException $e) {
				$request->session()->flash('error', "Some duplicates could not be imported");
			}
		}

		$request->session()->flash('status', "Finished importing RSS Items");
		return redirect()->action('RSSItemController@index');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create(Request $request)
	{
		return view('rss_items.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$rss_item = new RSSItem();

		$rss_item->text = $request->input("text");
		$rss_item->visible = $request->input("visible");
		$rss_item->expiration_date = $request->input("expiration_date");

		$rss_item->save();

		return redirect()->route('admin.rss_items.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$rss_item = RSSItem::findOrFail($id);

		return view('rss_items.show', compact('rss_item'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$rss_item = RSSItem::findOrFail($id);

		return view('rss_items.edit', compact('rss_item'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$rss_item = RSSItem::findOrFail($id);

		$rss_item->text = $request->input("text");
		$rss_item->visible = $request->input("visible");
		$rss_item->expiration_date = $request->input("expiration_date");

		$rss_item->save();

		return redirect()->route('admin.rss_items.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$rss_item = RSSItem::findOrFail($id);
		$rss_item->delete();

		return redirect()->route('admin.rss_items.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/rss_items/create.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> RSSItems / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('admin.rss_items.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('text')) has-error @endif">
                       <label for="text-field">Text</label>
                    <input type="text" id="text-field" name="text" class="form-control" value="{{ old("text") }}"/>
                       @if($errors->has("text"))
                        <span class="help-block">{{ $errors->first("text") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('visible')) has-error @endif">
                       <label for="visible-field">Visible</label>
                    <div class="btn-group" data-toggle="buttons"><label class="btn btn-primary"><input type="radio" value="true" name="visible" id="visible-field" autocomplete="off"> True</label><label class="btn btn-primary active"><input type="radio" name="visible" value="false" id="visible-field" autocomplete="off"> False</label></div>
                       @if($errors->has("visible"))
                        <span class="help-block">{{ $errors->first("visible") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('expiration_date')) has-error @endif">
                       <label for="expiration_date-field">Expiration_date</label>
                    <input type="text" id="expiration_date-field" name="expiration_date" class="form-control date-picker" value="{{ old("expiration_date") }}"/>
                       @if($errors->has("expiration_date"))
                        <span class="help-block">{{ $errors->first("expiration_date") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('admin.rss_items.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/rss_items/edit.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> RSSItems / Edit #{{$rss_item->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('admin.rss_items.update', $rss_item->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('text')) has-error @endif">
                       <label for="text-field">Text</label>
                    <input type="text" id="text-field" name="text" class="form-control" value="{{ is_null(old("text")) ? $rss_item->text : old("text") }}"/>
                       @if($errors->has("text"))
                        <span class="help-block">{{ $errors->first("text") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('visible')) has-error @endif">
                       <label for="visible-field">Visible</label>
                    <div class="btn-group" data-toggle="buttons"><label class="btn btn-primary"><input type="radio" value="true" name="visible" id="visible-field" autocomplete="off"> True</label><label class="btn btn-primary active"><input type="radio" name="visible" value="false" id="visible-field" autocomplete="off"> False</label></div>
                       @if($errors->has("visible"))
                        <span class="help-block">{{ $errors->first("visible") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('expiration_date')) has-error @endif">
                       <label for="expiration_date-field">Expiration_date</label>
                    <input type="text" id="expiration_date-field" name="expiration_date" class="form-control date-picker" value="{{ is_null(old("expiration_date")) ? $rss_item->expiration_date : old("expiration_date") }}"/>
                       @if($errors->has("expiration_date"))
                        <span class="help-block">{{ $errors->first("expiration_date") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('admin.rss_items.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/rss_items/index.blade.php
@extends('layouts.admin')
@section('title', 'UNHRD Dashboard - RSS Items')
@section('header')
    <div class="clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> RSSItems
            <a class="btn btn-success pull-right" href="{{ route('admin.rss_items.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
            <a class="btn btn-success pull-right" href="{{ route('admin.rss_items.import') }}"><i class="glyphicon glyphicon-plus"></i> Import</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($rss_items->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Text</th>
                        <th>Visible</th>
                        <th>Posted Date</th>
                        <th>Expiration Date</th>

                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($rss_items as $rss_item)
                            <tr>
                                <td>{{$rss_item->text}}</td>
                                <td>{{ $rss_item->visible ? 'Yes' : 'No' }}</td>
                                <td>{{$rss_item->posted_date}}</td>
                                <td>{{$rss_item->expiration_date}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.rss_items.show', $rss_item->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('admin.rss_items.edit', $rss_item->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('admin.rss_items.destroy', $rss_item->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $rss_items->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/rss_items/show.blade.php
@extends('layouts.admin')
@section('header')
<div class="clearfix">
        <h1>RSSItems / Show #{{$rss_item->id}}</h1>
        <form action="{{ route('admin.rss_items.destroy', $rss_item->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('admin.rss_items.edit', $rss_item->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                     <label for="text">Text</label>
                     <p class="form-control-static">{{$rss_item->text}}</p>
                </div>
                    <div class="form-group">
                     <label for="visible">Visible</label>
                     <p class="form-control-static">{{$rss_item->visible}}</p>
                </div>
                <div class="form-group">
                     <label for="expiration_date">Posted Date</label>
                     <p class="form-control-static">{{$rss_item->posted_date}}</p>
                </div>
                <div class="form-group">
                     <label for="expiration_date">Expiration Date</label>
                     <p class="form-control-static">{{$rss_item->expiration_date}}</p>
                </div>
                <div class="well well-sm clearfix">
                    <a class="btn btn-link pull-right" href="{{ route('admin.rss_items.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>
        </div>
    </div>

@endsection